### ISSUE TITLE
Plugin Broken with 3.1.2 ?

### ISSUE THREAD

**Issue by giviz** [CodeAndWeb/texturepacker-godot-plugin#10]
Each tpsheet import make Godot 3.1 not responding, the application has to be killed and restarted for it to import the next tpsheet which will again crash it and so on.

So right now, it's not usable at all :(

Is this plugin still maintained ?

**Comment by giviz** [comment]
The issue appear when at least 2 tpsheet files are present during the import, the first one is processed correctly and the second one freeze GoDot.

**Comment by CodeAndWeb** [comment]
Yes it is. You can try if the current version fixes the issue for you.
