### ISSUE TITLE
Clear the .sprites folder before generating tres files

### ISSUE THREAD

**Issue by njt1982** [CodeAndWeb/texturepacker-godot-plugin#11]
So I recently altered the output of Texture Packer sprite sheet (removed some unneeded files) however the importer plugin didn't wipe these out of the `.sprites` folder.

My fix was to manually delete all the `.tres` files and let GoDot rebuild them. But it'd be nice for it to "sync" properly.

**Comment by CodeAndWeb** [comment]
I see your point - but really want to keep the file system interactions as low as possible - especially when it comes to overwriting or deleting files.
