### ISSUE TITLE
Error enabling plugin in Godot 4.0

### ISSUE THREAD

**Issue by RicardRC** [CodeAndWeb/texturepacker-godot-plugin#18]
Unable to load addon script from path: 'res://addons/codeandweb.texturepacker/codeandweb.texturepacker_importer.gd' There seems to be an error in the code, please check the syntax.

I know Godot 4.0 it's still in active development, but we could have another branch of this repo to begin preparing for the new version.

**Comment by CodeAndWeb** [comment]
I've just updated the plugin. The code is already available from here... the asset store is waiting for approval.
