### ISSUE TITLE
Fail with Godot 4 beta API changed.

### ISSUE THREAD

**Issue by harrisyu** [CodeAndWeb/texturepacker-godot-plugin#22]
In Godot 4 change File & Directory to FileAccess & DirAccess.
Here is my fix patch.
[Fix texturepacker importer with godot 4 beta API change.zip](https://github.com/CodeAndWeb/texturepacker-godot-plugin/files/9766353/Fix.texturepacker.importer.with.godot.4.beta.API.change.zip)

**Comment by liangxiandan** [comment]
How to use it?

**Comment by harrisyu** [comment]
> How to use it?

Try follow this article:
https://www.specbee.com/blogs/how-create-and-apply-patch-git-diff-and-git-apply-commands-your-drupal-website

For me, I use an GUI frontend to apply patch.

**Comment by CodeAndWeb** [comment]
I've just merged the changes - thanks to @harrisyu.
