### ISSUE TITLE
[Bug]Segmentation error

### ISSUE THREAD

**Issue by H357753** [CodeAndWeb/texturepacker-godot-plugin#25]
My English is not very good, I am using translation software to communicate with you.
I got an error when cutting texture.
[texture.zip](https://github.com/CodeAndWeb/texturepacker-godot-plugin/files/14473128/texture.zip)
This is the material I used.
![1](https://github.com/CodeAndWeb/texturepacker-godot-plugin/assets/81468266/fae29328-75c0-4e1a-b1e5-f5e071f35f01)
Dislocation during cutting

**Comment by H357753** [comment]
[Uploading block_2.zip…]()
![block_4](https://github.com/CodeAndWeb/texturepacker-godot-plugin/assets/81468266/225496c5-08f0-4e76-8167-997eef846380)
This is the original material

**Comment by CodeAndWeb** [comment]
Hi,

sorry - can't help you with this. The plugin only supports [TexturePacker](https://www.codeandweb.com/texturepacker) - the files you provided were packed with some other software that we don't support.

Best
Andreas

**Comment by H357753** [comment]
ok,thanks
I will try texture packer
