### ISSUE TITLE
3.1 Polygon Support

### ISSUE THREAD

**Issue by avencherus** [CodeAndWeb/texturepacker-godot-plugin#3]
Any plans in the future to support the polygon packing feature for atlas export/import in the near future?

**Comment by CodeAndWeb** [comment]
We'd like to do that. But AFAIK there's not way to set polygon sprites in Godot (yet).

**Comment by avencherus** [comment]
Good to hear.  Having at least the options enabled to export polygons and the data would be nice, even if you don't have a solution for an importer just yet. 

Currently the polygon textures are done by applying textures on Polygon2D nodes.  They have Vector2 arrays for the polygon and the UVs.  In 3.1 the Skeleton2D and a weight editor was introduced to expand the functionality of them.

![godot_master_2018-10-10_04-35-46](https://user-images.githubusercontent.com/13004169/46708247-5b84b180-cc46-11e8-96b6-66dc897116b0.png)
![godot_master_2018-10-10_04-36-42](https://user-images.githubusercontent.com/13004169/46708249-5cb5de80-cc46-11e8-907f-1d053a2645b8.png)

If I had the atlases and vertex data, I could at least write a very hand tailored script to make use of it.   I only took a quick glance at exporting using the other engine templates, but was a bit unfamiliar with some of the options.

Given that these would be Node2Ds, I'm not sure what the preference would be for organizing and saving them.  Each texture could be a Polygon2D node constructed from data and saved as their own scenes, or even all together in a single scene like a palette.  I imagine there are probably even more elaborate ways to store the data part as custom Resources and have them construct the Polygon2D nodes when dragged into a scene.

**Comment by CodeAndWeb** [comment]
Yes - that's why we've added them. You should be able to modify the godot exporter easily.
Would be interested to see if you can make it work.

TexturePacker supports a quite big variety of frameworks - for us it's unfortunately not possible to dig deep into the frameworks without some insider knowledge... which you seem to have :)

**Comment by avencherus** [comment]
> Would be interested to see if you can make it work.

Outside of the context of a full fledged tool, it's not much to load the data into a Dictionary and set the data into a Polygon2D node.  Several lines of code if I recall.

However, for anyone stopping by, it's not a good idea to use polygons like this in Godot.  Polygon2D comes at a significant and quickly realized performance cost.

Upon investigating it, it's been a known issue for years.

~10x slower according to this person's benchmarking:  https://github.com/godotengine/godot/issues/19943

Sticking to rectangle region cuts from atlases is the better bet, and this may always be the case.
