### ISSUE TITLE
Support for Animated Tiles

### ISSUE THREAD

**Issue by r-lodahl** [CodeAndWeb/texturepacker-godot-plugin#6]
As TexturePacker already has the feature below, feature request in short: enable animated tile groups export/import for the godot plugin.

-----------------------------------------
In Godot a 2d-sprite-Animation can be defined by using a single sprite and setting a number of columns and rows. This sprite can also be contained in an Atlas Texture. My idea/request: Make it possible to mark multiple images as an single animation, which then will be added to the atlas texture by texturepacker using a strict column/row layout (only this subimage, not the whole atlas). When importing just detect the sub-image as animation and configure it in that way.

why: the animated tile in godots tilemap is much more performant than calling set_tile every frame for every animated tile.

**Comment by CodeAndWeb** [comment]
I've added this to the backlog of TexturePacker. We'll add the feature as soon as we get more requests from users.
