### ISSUE TITLE
Import Presets for Texture Flags

### ISSUE THREAD

**Issue by thejustinwalsh** [CodeAndWeb/texturepacker-godot-plugin#8]
When importing the texture atlas, the Filter texture flag is on by default. When wanting your sprites to appear more pixelated it is desirable to turn the Filter flag off. Additionally, adding support for other Texture flags in the presets would be ideal.

The [Tiled Plugin](https://github.com/vnen/godot-tiled-importer) is an excellent example of how to handle import presets and Texture Flags.

**Comment by CodeAndWeb** [comment]
Looks useful. I unfortunately have no resources at the moment to add this feature... pull request welcome :)
